### ISSUE TITLE
bouncy plots on Magora

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/magora#122] opened 2022-06-15 19:36 UTC
I've noticed that the plots seem to bounce around on the screen sometimes. See screen recording.

https://user-images.githubusercontent.com/40642407/173909730-69d0e31a-ea38-40da-a369-bb26611cc6f9.mov

Wondering if this is 
a) something others can reproduce, and if so 
b) whether this might be a Shiny issue or something else...?

cc @sharlagelfand @j-hendrickson-sage @JessterB

**Comment by JessterB** [comment] 2022-06-15 19:42
a) Yes, I see the bouncing
b) I'm not sure yet, but it's really weird

**Comment by JessterB** [comment] 2022-06-15 20:20
It looks like this behavior is tied to the loading spinner (<div id="spinner-cb2d59d4eac3a93f3c7ca32cc7acc9ba" class="loader">Loading...</div>), for what that's worth:

https://user-images.githubusercontent.com/89862046/173919093-3754a75c-ce27-478d-a662-5016aa5fbc0b.mov

**Comment by sharlagelfand** [comment] 2022-06-21 13:35
I'm not able to reproduce unfortunately! What browser are folks using?

If it's tied to the spinner, we can always remove it - it just indicates that the plot is loading, but these ones load fairly quickly so might not be needed. Would be curious how this scales with more users though, i.e. if the plots take longer to load, we might still want the spinner.

**Comment by sharlagelfand** [comment] 2022-07-06 15:06
Closed by #125.

**Closed by sharlagelfand** 2022-07-06 15:06 UTC
